classname=net.bhswat.wurm.riftmod.RiftMod
classpath=riftmod.jar

TICK = 60

// Rift timer
resheduleRiftTimerOnStart = true
// Must be [1 to 7] where 1 it is Monday and 7 it is Sunday
scheduleRiftInDayOfWeek = 3
scheduleRiftAtHour = 23

findspot.tries = 100
findspot.maxHeightDiff = 300
findspot.default.x = 2100
findspot.default.y = 1600

resource.weight = 1000
decorationChance = 15
//riftFirstDelay = 180
riftFirstDelay = 0
riftWaveDelay = 1
//bellTime = 360
//riftEndDelay = 360
bellTime = 10
riftEndDelay = 10
riftFinishDelay = 60
spawnerTick = 10
radius = 30
lump.weight = 15000
shoulder.chance = 10
accessory.chance = 10
mask.chance = 10
coins.normalfs = 50
coins.normalcoins = 200
coins.highfs = 70
coins.additionalcoins = 300

wave1.beast     = 15
wave1.jackal    = 0
wave1.ogre      = 5
wave1.warmaster = 0
wave1.caster    = 10
wave1.ogreMage  = 5
wave1.summoner  = 0

wave2.beast     = 5
wave2.jackal    = 10
wave2.ogre      = 0
wave2.warmaster = 0
wave2.caster    = 15
wave2.ogreMage  = 5
wave2.summoner  = 0

wave3.beast     = 0
wave3.jackal    = 0
wave3.ogre      = 0
wave3.warmaster = 1
wave3.caster    = 0
wave3.ogreMage  = 0
wave3.summoner  = 0